/*
------------------------------------------------------------
Project: New Wheels Sales Analysis
Question 7: Calculate the net revenue generated by the company
and determine the quarter-over-quarter percentage change in net revenue.
------------------------------------------------------------
*/

-- 7A. Calculate total net revenue
SELECT 
    SUM(quantity * (vehicle_price - ((discount / 100) * vehicle_price))) AS net_revenue
FROM 
    order_t;

-- 7B. Calculate net revenue and quarter-over-quarter % change
SELECT 
    quarter_number,
    ROUND(SUM(quantity * (vehicle_price - discount)), 2) AS net_revenue, 
    ROUND(
        (
            (SUM(quantity * (vehicle_price - discount))
            - LAG(SUM(quantity * (vehicle_price - discount))) OVER (ORDER BY quarter_number))
            / LAG(SUM(quantity * (vehicle_price - discount))) OVER (ORDER BY quarter_number)
        ) * 100, 
        2
    ) AS qoq_pct_change
FROM 
    order_t
GROUP BY 
    quarter_number
ORDER BY 
    quarter_number;

------------------------------------------------------------
-- Observations and Insights:
-- • Total orders decreased by approximately 36% from Q1 to Q4, mirroring the decline in customer satisfaction.
-- • Q3 showed a slight decline of 10.57%, indicating temporary stabilization before a sharper drop in Q4.
-- • Seasonal purchase patterns, shipping logistics, customer satisfaction, and pricing strategies may influence revenue trends.
-- • Recommendation: Conduct deeper analysis on drivers of revenue decline and develop strategies to stabilize and grow revenue in the next fiscal year.
------------------------------------------------------------
